[versions]
agp = "8.13.2"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
hilt = "2.56.2"
navigationUiKtx = "2.9.6"
composeBom = "2024.09.00"
compose_lottie = "6.0.0"
coil-compose ="2.7.0"
viewmodel-compose = "2.10.0"
chucker = "4.3.0"
gson = "2.11.0"
converterGson = "2.11.0"
okhttp = "4.12.0"
resultat = "1.0.0"
loggingInterceptor = "4.12.0"
kotlinxCoroutinesAndroid = "1.9.0"
kotlinxCoroutinesCore = "1.9.0"
retrofit2KotlinCoroutinesAdapter = "0.9.2"
room = "2.7.2"
jsoup = "1.12.1"
compose_navigation = "2.7.5"
calendar = "2.10.0"
navigation-compose = "1.3.0"
hiltCommon = "1.2.0"
hiltWork = "1.2.0"
navigation3 = "1.0.0"
ksp = "2.3.2"
kotlinxSerialization = "1.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata"}
android-lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "compose_lottie"}
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation"}
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout"}
compose-material-icons = { module = "androidx.compose.material:material-icons-extended"}
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose"}
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewmodel-compose"}
android-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "compose_navigation"}
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

github-chucker-debug = {module ="com.github.chuckerteam.chucker:library", version.ref = "chucker" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
resultat = { module = "fr.haan.resultat:resultat", version.ref = "resultat" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterGson" }
adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "converterGson" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
converter-simplexml = { module = "com.squareup.retrofit2:converter-simplexml", version.ref = "converterGson" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
retrofit2-kotlin-coroutines-adapter = { module = "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter", version.ref = "retrofit2KotlinCoroutinesAdapter" }

room-rumtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
kizitonwose-calendar = {module = "com.kizitonwose.calendar:compose", version.ref = "calendar"}
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "navigation-compose"}
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCommon" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigationUiKtx" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerialization" }

